// <auto-generated />
using System;
using ETourProject1.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETourProject1.Migrations
{
    [DbContext(typeof(Appdbcontext))]
    [Migration("20230828182216_Cost_MasterInitial")]
    partial class Cost_MasterInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ETourProject1.Models.Cost_Master", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostId"));

                    b.Property<int>("ChildWithBed")
                        .HasColumnType("int");

                    b.Property<int>("ChildWithoutBed")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("ExtraPersonCost")
                        .HasColumnType("int");

                    b.Property<int>("SinglePersonCost")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("pkgId")
                        .HasColumnType("int");

                    b.HasKey("CostId");

                    b.ToTable("Cost_Master");
                });
#pragma warning restore 612, 618
        }
    }
}
